In [ ]:
Задание 1.
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [15]:
N = int(input())
x = np.arange( 0, N)
reversed_x = x[::-1]
reversed_x

10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
Задание 2.
Создайте диагональную матрицу с элементами от N до 0. 
Посчитайте сумму ее значений на диагонали.

In [29]:
N = int(input())
a = np.diag(np.arange(N+1))
print(a)
sum(a.diagonal())

10
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0  0 10]]


55

In [ ]:
Задание 3.
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
Определите какому фильму было выставлено больше всего оценок 5.0.

In [35]:
import pandas as pd

In [215]:
#вариант через сводную: потому что я - эксельный аналитик)
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
Total = ratings.merge(movies, on=["movieId"], how='inner')
Total_filt = Total[(Total['rating']==5)]
pvt = Total_filt.pivot_table(index=['title','movieId'], values = 'rating', aggfunc='count')
max_count = pvt['rating'].max()
Final = pvt[(pvt['rating']==max_count)]
Final

rating
title                            movieId        
Shawshank Redemption, The (1994) 318         153

In [185]:
#вариант через группировку
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
Total = ratings.merge(movies, on=["movieId"], how='inner')
Total_filt = Total[(Total['rating']==5)]
Total_group = Total_filt.groupby(['title'])['rating'].count().reset_index(name='Count')
Total_group.head()
max_count = Total_group['Count'].max()
Final = Total_group[(Total_group['Count']==max_count)]
Final

title  Count
2310  Shawshank Redemption, The (1994)    153

In [181]:
#а это я сначала непраивльно прочитала задание)
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
Total = ratings.merge(movies, on=["movieId"], how='inner')
Total.to_csv("Total.csv",index=False)
Total_filt = Total.filter(items = ['movieId', 'rating','title'])
Total_filt.head()
Average_rating = Total_filt.groupby(['title'])['rating'].mean().reset_index(name='AverageRating')
max_rating = Average_rating['AverageRating'].max()
max_rating = int(max_rating)
Average_rating['AverageRating'] = Average_rating['AverageRating'].apply(int)
Average_rating[Average_rating.AverageRating>=max_rating].head()

title  AverageRating
3                 'Salem's Lot (2004)              5
35                12 Angry Men (1997)              5
37                   12 Chairs (1976)              5
68   20 Million Miles to Earth (1957)              5
131                        61* (2001)              5

In [ ]:
Задание 4.
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики 
(Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. 
Не учитывайте в расчетах отрицательные значения quantity.

In [132]:
power = pd.read_csv('power.csv')

In [133]:
power.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [150]:
baltic_states = power[((power['country']=='Latvia') | (power['country']=='Litva') | (power['country']=='Estonia')) & ((power['year']>=2005) & (power['year']<=2010))& ((power['category']==4) | (power['category']==12)  | (power['category']==21))& (power['quantity']>=0)]
baltic_states['quantity'].sum()

118284.0

In [ ]:
Задание 5.
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [30]:
left = np.array( [ [4, 2,1], [1, 3,0] , [0, 5,4]] )

In [31]:
right = np.array( [4, 12,-3] )

In [32]:
from numpy import linalg

In [33]:
linalg.solve(left, right)

array([ 0.46666667,  3.84444444, -5.55555556])

In [34]:
np.allclose( np.dot(left, linalg.solve(left, right)), right )

True